name: Release

on:
  push:
    branches:
      - main
    tags:
      - "*"

jobs:
  build:
    runs-on: [self-hosted, '${{ github.repository }}']
    steps:
      - uses: actions/checkout@v4

      - name: Create Package
        uses: BigWigsMods/packager@v2
        env:
          #CF_API_KEY: ${{ secrets.CF_API_KEY }}
          #WAGO_API_TOKEN: ${{ secrets.WAGO_API_TOKEN }}
          GITHUB_OAUTH: ${{ secrets.GH_TOKEN }}

      - uses: actions/upload-artifact@v4
        with:
          name: ActivateWindows-test
          path: .release/
          include-hidden-files: true